/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateDashboardRouteRouteImport } from './routes/(private)/_dashboard/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAuthRouteRouteImport } from './routes/(public)/_auth/route'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as privateDashboardDashboardRouteImport } from './routes/(private)/_dashboard/dashboard'
import { Route as publicAuthSigninRouteImport } from './routes/(public)/_auth/signin'
import { Route as publicAuthSignupRouteImport } from './routes/(public)/_auth/signup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as privateDashboardGymsGymIdRouteImport } from './routes/(private)/_dashboard/gyms/$gymId'
import { Route as privateDashboardGymsCreateRouteImport } from './routes/(private)/_dashboard/gyms/create'
import { Route as privateDashboardGymsListRouteImport } from './routes/(private)/_dashboard/gyms/list'

const privateDashboardRouteRoute = privateDashboardRouteRouteImport.update({
  id: '/(private)/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthRouteRoute = publicAuthRouteRouteImport.update({
  id: '/(public)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const privateDashboardDashboardRoute =
  privateDashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const publicAuthSigninRoute = publicAuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => publicAuthRouteRoute,
} as any)
const publicAuthSignupRoute = publicAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => publicAuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const privateDashboardGymsGymIdRoute =
  privateDashboardGymsGymIdRouteImport.update({
    id: '/gyms/$gymId',
    path: '/gyms/$gymId',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardGymsCreateRoute =
  privateDashboardGymsCreateRouteImport.update({
    id: '/gyms/create',
    path: '/gyms/create',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardGymsListRoute =
  privateDashboardGymsListRouteImport.update({
    id: '/gyms/list',
    path: '/gyms/list',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/api/$': typeof ApiSplatRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof privateDashboardDashboardRoute
  '/signin': typeof publicAuthSigninRoute
  '/signup': typeof publicAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/gyms/$gymId': typeof privateDashboardGymsGymIdRoute
  '/gyms/create': typeof privateDashboardGymsCreateRoute
  '/gyms/list': typeof privateDashboardGymsListRoute
}
export interface FileRoutesByTo {
  '/api/$': typeof ApiSplatRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof privateDashboardDashboardRoute
  '/signin': typeof publicAuthSigninRoute
  '/signup': typeof publicAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/gyms/$gymId': typeof privateDashboardGymsGymIdRoute
  '/gyms/create': typeof privateDashboardGymsCreateRoute
  '/gyms/list': typeof privateDashboardGymsListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)/_dashboard': typeof privateDashboardRouteRouteWithChildren
  '/(public)/_auth': typeof publicAuthRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/(public)/': typeof publicIndexRoute
  '/(private)/_dashboard/dashboard': typeof privateDashboardDashboardRoute
  '/(public)/_auth/signin': typeof publicAuthSigninRoute
  '/(public)/_auth/signup': typeof publicAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/(private)/_dashboard/gyms/$gymId': typeof privateDashboardGymsGymIdRoute
  '/(private)/_dashboard/gyms/create': typeof privateDashboardGymsCreateRoute
  '/(private)/_dashboard/gyms/list': typeof privateDashboardGymsListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/$'
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/gyms/$gymId'
    | '/gyms/create'
    | '/gyms/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/$'
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/gyms/$gymId'
    | '/gyms/create'
    | '/gyms/list'
  id:
    | '__root__'
    | '/(private)/_dashboard'
    | '/(public)/_auth'
    | '/api/$'
    | '/(public)/'
    | '/(private)/_dashboard/dashboard'
    | '/(public)/_auth/signin'
    | '/(public)/_auth/signup'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/(private)/_dashboard/gyms/$gymId'
    | '/(private)/_dashboard/gyms/create'
    | '/(private)/_dashboard/gyms/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateDashboardRouteRoute: typeof privateDashboardRouteRouteWithChildren
  publicAuthRouteRoute: typeof publicAuthRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  publicIndexRoute: typeof publicIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)/_dashboard': {
      id: '/(private)/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_auth': {
      id: '/(public)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_dashboard/dashboard': {
      id: '/(private)/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privateDashboardDashboardRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(public)/_auth/signin': {
      id: '/(public)/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof publicAuthSigninRouteImport
      parentRoute: typeof publicAuthRouteRoute
    }
    '/(public)/_auth/signup': {
      id: '/(public)/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicAuthSignupRouteImport
      parentRoute: typeof publicAuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_dashboard/gyms/$gymId': {
      id: '/(private)/_dashboard/gyms/$gymId'
      path: '/gyms/$gymId'
      fullPath: '/gyms/$gymId'
      preLoaderRoute: typeof privateDashboardGymsGymIdRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/gyms/create': {
      id: '/(private)/_dashboard/gyms/create'
      path: '/gyms/create'
      fullPath: '/gyms/create'
      preLoaderRoute: typeof privateDashboardGymsCreateRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/gyms/list': {
      id: '/(private)/_dashboard/gyms/list'
      path: '/gyms/list'
      fullPath: '/gyms/list'
      preLoaderRoute: typeof privateDashboardGymsListRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
  }
}

interface privateDashboardRouteRouteChildren {
  privateDashboardDashboardRoute: typeof privateDashboardDashboardRoute
  privateDashboardGymsGymIdRoute: typeof privateDashboardGymsGymIdRoute
  privateDashboardGymsCreateRoute: typeof privateDashboardGymsCreateRoute
  privateDashboardGymsListRoute: typeof privateDashboardGymsListRoute
}

const privateDashboardRouteRouteChildren: privateDashboardRouteRouteChildren = {
  privateDashboardDashboardRoute: privateDashboardDashboardRoute,
  privateDashboardGymsGymIdRoute: privateDashboardGymsGymIdRoute,
  privateDashboardGymsCreateRoute: privateDashboardGymsCreateRoute,
  privateDashboardGymsListRoute: privateDashboardGymsListRoute,
}

const privateDashboardRouteRouteWithChildren =
  privateDashboardRouteRoute._addFileChildren(
    privateDashboardRouteRouteChildren,
  )

interface publicAuthRouteRouteChildren {
  publicAuthSigninRoute: typeof publicAuthSigninRoute
  publicAuthSignupRoute: typeof publicAuthSignupRoute
}

const publicAuthRouteRouteChildren: publicAuthRouteRouteChildren = {
  publicAuthSigninRoute: publicAuthSigninRoute,
  publicAuthSignupRoute: publicAuthSignupRoute,
}

const publicAuthRouteRouteWithChildren = publicAuthRouteRoute._addFileChildren(
  publicAuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateDashboardRouteRoute: privateDashboardRouteRouteWithChildren,
  publicAuthRouteRoute: publicAuthRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  publicIndexRoute: publicIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
