/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateDashboardRouteRouteImport } from './routes/(private)/_dashboard/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAuthRouteRouteImport } from './routes/(public)/_auth/route'
import { Route as publicVerifyEmailRouteImport } from './routes/(public)/verify-email'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as privateDashboardAdminRouteRouteImport } from './routes/(private)/_dashboard/_admin/route'
import { Route as privateDashboardBodyWeightRouteRouteImport } from './routes/(private)/_dashboard/body-weight/route'
import { Route as privateDashboardDashboardRouteImport } from './routes/(private)/_dashboard/dashboard'
import { Route as privateDashboardGymsRouteRouteImport } from './routes/(private)/_dashboard/gyms/route'
import { Route as privateDashboardSchedulesRouteRouteImport } from './routes/(private)/_dashboard/schedules/route'
import { Route as privateDashboardWorkoutsRouteRouteImport } from './routes/(private)/_dashboard/workouts/route'
import { Route as publicAuthForgotPasswordRouteImport } from './routes/(public)/_auth/forgot-password'
import { Route as publicAuthResetPasswordRouteImport } from './routes/(public)/_auth/reset-password'
import { Route as publicAuthSigninRouteImport } from './routes/(public)/_auth/signin'
import { Route as publicAuthSignupRouteImport } from './routes/(public)/_auth/signup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as privateDashboardAdminExercisesRouteRouteImport } from './routes/(private)/_dashboard/_admin/exercises/route'
import { Route as privateDashboardAdminMuscleGroupsRouteRouteImport } from './routes/(private)/_dashboard/_admin/muscle-groups/route'
import { Route as privateDashboardBodyWeightIndexRouteImport } from './routes/(private)/_dashboard/body-weight/index'
import { Route as privateDashboardBodyWeightBodyWeightIdRouteImport } from './routes/(private)/_dashboard/body-weight/$bodyWeightId'
import { Route as privateDashboardBodyWeightCreateRouteImport } from './routes/(private)/_dashboard/body-weight/create'
import { Route as privateDashboardExerciseLogIndexRouteImport } from './routes/(private)/_dashboard/exercise-log/index'
import { Route as privateDashboardExercisesIndexRouteImport } from './routes/(private)/_dashboard/exercises/index'
import { Route as privateDashboardGymsIndexRouteImport } from './routes/(private)/_dashboard/gyms/index'
import { Route as privateDashboardGymsGymIdRouteImport } from './routes/(private)/_dashboard/gyms/$gymId'
import { Route as privateDashboardGymsCreateRouteImport } from './routes/(private)/_dashboard/gyms/create'
import { Route as privateDashboardSchedulesIndexRouteImport } from './routes/(private)/_dashboard/schedules/index'
import { Route as privateDashboardSchedulesScheduleIdRouteImport } from './routes/(private)/_dashboard/schedules/$scheduleId'
import { Route as privateDashboardSchedulesCreateRouteImport } from './routes/(private)/_dashboard/schedules/create'
import { Route as privateDashboardSessionsSessionIdRouteImport } from './routes/(private)/_dashboard/sessions/$sessionId'
import { Route as privateDashboardWorkoutsIndexRouteImport } from './routes/(private)/_dashboard/workouts/index'
import { Route as privateDashboardWorkoutsWorkoutIdRouteImport } from './routes/(private)/_dashboard/workouts/$workoutId'
import { Route as privateDashboardWorkoutsCreateRouteImport } from './routes/(private)/_dashboard/workouts/create'
import { Route as privateDashboardAdminExercisesExerciseIdRouteImport } from './routes/(private)/_dashboard/_admin/exercises/$exerciseId'
import { Route as privateDashboardAdminExercisesCreateRouteImport } from './routes/(private)/_dashboard/_admin/exercises/create'
import { Route as privateDashboardAdminMuscleGroupsIndexRouteImport } from './routes/(private)/_dashboard/_admin/muscle-groups/index'
import { Route as privateDashboardAdminMuscleGroupsMuscleGroupIdRouteImport } from './routes/(private)/_dashboard/_admin/muscle-groups/$muscleGroupId'
import { Route as privateDashboardAdminMuscleGroupsCreateRouteImport } from './routes/(private)/_dashboard/_admin/muscle-groups/create'

const privateDashboardRouteRoute = privateDashboardRouteRouteImport.update({
  id: '/(private)/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthRouteRoute = publicAuthRouteRouteImport.update({
  id: '/(public)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const publicVerifyEmailRoute = publicVerifyEmailRouteImport.update({
  id: '/(public)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const privateDashboardAdminRouteRoute =
  privateDashboardAdminRouteRouteImport.update({
    id: '/_admin',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardBodyWeightRouteRoute =
  privateDashboardBodyWeightRouteRouteImport.update({
    id: '/body-weight',
    path: '/body-weight',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardDashboardRoute =
  privateDashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardGymsRouteRoute =
  privateDashboardGymsRouteRouteImport.update({
    id: '/gyms',
    path: '/gyms',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardSchedulesRouteRoute =
  privateDashboardSchedulesRouteRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardWorkoutsRouteRoute =
  privateDashboardWorkoutsRouteRouteImport.update({
    id: '/workouts',
    path: '/workouts',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const publicAuthForgotPasswordRoute =
  publicAuthForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => publicAuthRouteRoute,
  } as any)
const publicAuthResetPasswordRoute = publicAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => publicAuthRouteRoute,
} as any)
const publicAuthSigninRoute = publicAuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => publicAuthRouteRoute,
} as any)
const publicAuthSignupRoute = publicAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => publicAuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const privateDashboardAdminExercisesRouteRoute =
  privateDashboardAdminExercisesRouteRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => privateDashboardAdminRouteRoute,
  } as any)
const privateDashboardAdminMuscleGroupsRouteRoute =
  privateDashboardAdminMuscleGroupsRouteRouteImport.update({
    id: '/muscle-groups',
    path: '/muscle-groups',
    getParentRoute: () => privateDashboardAdminRouteRoute,
  } as any)
const privateDashboardBodyWeightIndexRoute =
  privateDashboardBodyWeightIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privateDashboardBodyWeightRouteRoute,
  } as any)
const privateDashboardBodyWeightBodyWeightIdRoute =
  privateDashboardBodyWeightBodyWeightIdRouteImport.update({
    id: '/$bodyWeightId',
    path: '/$bodyWeightId',
    getParentRoute: () => privateDashboardBodyWeightRouteRoute,
  } as any)
const privateDashboardBodyWeightCreateRoute =
  privateDashboardBodyWeightCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => privateDashboardBodyWeightRouteRoute,
  } as any)
const privateDashboardExerciseLogIndexRoute =
  privateDashboardExerciseLogIndexRouteImport.update({
    id: '/exercise-log/',
    path: '/exercise-log/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardExercisesIndexRoute =
  privateDashboardExercisesIndexRouteImport.update({
    id: '/exercises/',
    path: '/exercises/',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardGymsIndexRoute =
  privateDashboardGymsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privateDashboardGymsRouteRoute,
  } as any)
const privateDashboardGymsGymIdRoute =
  privateDashboardGymsGymIdRouteImport.update({
    id: '/$gymId',
    path: '/$gymId',
    getParentRoute: () => privateDashboardGymsRouteRoute,
  } as any)
const privateDashboardGymsCreateRoute =
  privateDashboardGymsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => privateDashboardGymsRouteRoute,
  } as any)
const privateDashboardSchedulesIndexRoute =
  privateDashboardSchedulesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privateDashboardSchedulesRouteRoute,
  } as any)
const privateDashboardSchedulesScheduleIdRoute =
  privateDashboardSchedulesScheduleIdRouteImport.update({
    id: '/$scheduleId',
    path: '/$scheduleId',
    getParentRoute: () => privateDashboardSchedulesRouteRoute,
  } as any)
const privateDashboardSchedulesCreateRoute =
  privateDashboardSchedulesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => privateDashboardSchedulesRouteRoute,
  } as any)
const privateDashboardSessionsSessionIdRoute =
  privateDashboardSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => privateDashboardRouteRoute,
  } as any)
const privateDashboardWorkoutsIndexRoute =
  privateDashboardWorkoutsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privateDashboardWorkoutsRouteRoute,
  } as any)
const privateDashboardWorkoutsWorkoutIdRoute =
  privateDashboardWorkoutsWorkoutIdRouteImport.update({
    id: '/$workoutId',
    path: '/$workoutId',
    getParentRoute: () => privateDashboardWorkoutsRouteRoute,
  } as any)
const privateDashboardWorkoutsCreateRoute =
  privateDashboardWorkoutsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => privateDashboardWorkoutsRouteRoute,
  } as any)
const privateDashboardAdminExercisesExerciseIdRoute =
  privateDashboardAdminExercisesExerciseIdRouteImport.update({
    id: '/$exerciseId',
    path: '/$exerciseId',
    getParentRoute: () => privateDashboardAdminExercisesRouteRoute,
  } as any)
const privateDashboardAdminExercisesCreateRoute =
  privateDashboardAdminExercisesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => privateDashboardAdminExercisesRouteRoute,
  } as any)
const privateDashboardAdminMuscleGroupsIndexRoute =
  privateDashboardAdminMuscleGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => privateDashboardAdminMuscleGroupsRouteRoute,
  } as any)
const privateDashboardAdminMuscleGroupsMuscleGroupIdRoute =
  privateDashboardAdminMuscleGroupsMuscleGroupIdRouteImport.update({
    id: '/$muscleGroupId',
    path: '/$muscleGroupId',
    getParentRoute: () => privateDashboardAdminMuscleGroupsRouteRoute,
  } as any)
const privateDashboardAdminMuscleGroupsCreateRoute =
  privateDashboardAdminMuscleGroupsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => privateDashboardAdminMuscleGroupsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/verify-email': typeof publicVerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof publicIndexRoute
  '/body-weight': typeof privateDashboardBodyWeightRouteRouteWithChildren
  '/gyms': typeof privateDashboardGymsRouteRouteWithChildren
  '/schedules': typeof privateDashboardSchedulesRouteRouteWithChildren
  '/workouts': typeof privateDashboardWorkoutsRouteRouteWithChildren
  '/dashboard': typeof privateDashboardDashboardRoute
  '/forgot-password': typeof publicAuthForgotPasswordRoute
  '/reset-password': typeof publicAuthResetPasswordRoute
  '/signin': typeof publicAuthSigninRoute
  '/signup': typeof publicAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/exercises': typeof privateDashboardAdminExercisesRouteRouteWithChildren
  '/muscle-groups': typeof privateDashboardAdminMuscleGroupsRouteRouteWithChildren
  '/body-weight/$bodyWeightId': typeof privateDashboardBodyWeightBodyWeightIdRoute
  '/body-weight/create': typeof privateDashboardBodyWeightCreateRoute
  '/gyms/$gymId': typeof privateDashboardGymsGymIdRoute
  '/gyms/create': typeof privateDashboardGymsCreateRoute
  '/schedules/$scheduleId': typeof privateDashboardSchedulesScheduleIdRoute
  '/schedules/create': typeof privateDashboardSchedulesCreateRoute
  '/sessions/$sessionId': typeof privateDashboardSessionsSessionIdRoute
  '/workouts/$workoutId': typeof privateDashboardWorkoutsWorkoutIdRoute
  '/workouts/create': typeof privateDashboardWorkoutsCreateRoute
  '/body-weight/': typeof privateDashboardBodyWeightIndexRoute
  '/exercise-log/': typeof privateDashboardExerciseLogIndexRoute
  '/exercises/': typeof privateDashboardExercisesIndexRoute
  '/gyms/': typeof privateDashboardGymsIndexRoute
  '/schedules/': typeof privateDashboardSchedulesIndexRoute
  '/workouts/': typeof privateDashboardWorkoutsIndexRoute
  '/exercises/$exerciseId': typeof privateDashboardAdminExercisesExerciseIdRoute
  '/exercises/create': typeof privateDashboardAdminExercisesCreateRoute
  '/muscle-groups/$muscleGroupId': typeof privateDashboardAdminMuscleGroupsMuscleGroupIdRoute
  '/muscle-groups/create': typeof privateDashboardAdminMuscleGroupsCreateRoute
  '/muscle-groups/': typeof privateDashboardAdminMuscleGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/verify-email': typeof publicVerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof privateDashboardDashboardRoute
  '/forgot-password': typeof publicAuthForgotPasswordRoute
  '/reset-password': typeof publicAuthResetPasswordRoute
  '/signin': typeof publicAuthSigninRoute
  '/signup': typeof publicAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/exercises': typeof privateDashboardExercisesIndexRoute
  '/body-weight/$bodyWeightId': typeof privateDashboardBodyWeightBodyWeightIdRoute
  '/body-weight/create': typeof privateDashboardBodyWeightCreateRoute
  '/gyms/$gymId': typeof privateDashboardGymsGymIdRoute
  '/gyms/create': typeof privateDashboardGymsCreateRoute
  '/schedules/$scheduleId': typeof privateDashboardSchedulesScheduleIdRoute
  '/schedules/create': typeof privateDashboardSchedulesCreateRoute
  '/sessions/$sessionId': typeof privateDashboardSessionsSessionIdRoute
  '/workouts/$workoutId': typeof privateDashboardWorkoutsWorkoutIdRoute
  '/workouts/create': typeof privateDashboardWorkoutsCreateRoute
  '/body-weight': typeof privateDashboardBodyWeightIndexRoute
  '/exercise-log': typeof privateDashboardExerciseLogIndexRoute
  '/gyms': typeof privateDashboardGymsIndexRoute
  '/schedules': typeof privateDashboardSchedulesIndexRoute
  '/workouts': typeof privateDashboardWorkoutsIndexRoute
  '/exercises/$exerciseId': typeof privateDashboardAdminExercisesExerciseIdRoute
  '/exercises/create': typeof privateDashboardAdminExercisesCreateRoute
  '/muscle-groups/$muscleGroupId': typeof privateDashboardAdminMuscleGroupsMuscleGroupIdRoute
  '/muscle-groups/create': typeof privateDashboardAdminMuscleGroupsCreateRoute
  '/muscle-groups': typeof privateDashboardAdminMuscleGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)/_dashboard': typeof privateDashboardRouteRouteWithChildren
  '/(public)/_auth': typeof publicAuthRouteRouteWithChildren
  '/(public)/verify-email': typeof publicVerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/(public)/': typeof publicIndexRoute
  '/(private)/_dashboard/_admin': typeof privateDashboardAdminRouteRouteWithChildren
  '/(private)/_dashboard/body-weight': typeof privateDashboardBodyWeightRouteRouteWithChildren
  '/(private)/_dashboard/gyms': typeof privateDashboardGymsRouteRouteWithChildren
  '/(private)/_dashboard/schedules': typeof privateDashboardSchedulesRouteRouteWithChildren
  '/(private)/_dashboard/workouts': typeof privateDashboardWorkoutsRouteRouteWithChildren
  '/(private)/_dashboard/dashboard': typeof privateDashboardDashboardRoute
  '/(public)/_auth/forgot-password': typeof publicAuthForgotPasswordRoute
  '/(public)/_auth/reset-password': typeof publicAuthResetPasswordRoute
  '/(public)/_auth/signin': typeof publicAuthSigninRoute
  '/(public)/_auth/signup': typeof publicAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/(private)/_dashboard/_admin/exercises': typeof privateDashboardAdminExercisesRouteRouteWithChildren
  '/(private)/_dashboard/_admin/muscle-groups': typeof privateDashboardAdminMuscleGroupsRouteRouteWithChildren
  '/(private)/_dashboard/body-weight/$bodyWeightId': typeof privateDashboardBodyWeightBodyWeightIdRoute
  '/(private)/_dashboard/body-weight/create': typeof privateDashboardBodyWeightCreateRoute
  '/(private)/_dashboard/gyms/$gymId': typeof privateDashboardGymsGymIdRoute
  '/(private)/_dashboard/gyms/create': typeof privateDashboardGymsCreateRoute
  '/(private)/_dashboard/schedules/$scheduleId': typeof privateDashboardSchedulesScheduleIdRoute
  '/(private)/_dashboard/schedules/create': typeof privateDashboardSchedulesCreateRoute
  '/(private)/_dashboard/sessions/$sessionId': typeof privateDashboardSessionsSessionIdRoute
  '/(private)/_dashboard/workouts/$workoutId': typeof privateDashboardWorkoutsWorkoutIdRoute
  '/(private)/_dashboard/workouts/create': typeof privateDashboardWorkoutsCreateRoute
  '/(private)/_dashboard/body-weight/': typeof privateDashboardBodyWeightIndexRoute
  '/(private)/_dashboard/exercise-log/': typeof privateDashboardExerciseLogIndexRoute
  '/(private)/_dashboard/exercises/': typeof privateDashboardExercisesIndexRoute
  '/(private)/_dashboard/gyms/': typeof privateDashboardGymsIndexRoute
  '/(private)/_dashboard/schedules/': typeof privateDashboardSchedulesIndexRoute
  '/(private)/_dashboard/workouts/': typeof privateDashboardWorkoutsIndexRoute
  '/(private)/_dashboard/_admin/exercises/$exerciseId': typeof privateDashboardAdminExercisesExerciseIdRoute
  '/(private)/_dashboard/_admin/exercises/create': typeof privateDashboardAdminExercisesCreateRoute
  '/(private)/_dashboard/_admin/muscle-groups/$muscleGroupId': typeof privateDashboardAdminMuscleGroupsMuscleGroupIdRoute
  '/(private)/_dashboard/_admin/muscle-groups/create': typeof privateDashboardAdminMuscleGroupsCreateRoute
  '/(private)/_dashboard/_admin/muscle-groups/': typeof privateDashboardAdminMuscleGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/verify-email'
    | '/api/$'
    | '/'
    | '/body-weight'
    | '/gyms'
    | '/schedules'
    | '/workouts'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/exercises'
    | '/muscle-groups'
    | '/body-weight/$bodyWeightId'
    | '/body-weight/create'
    | '/gyms/$gymId'
    | '/gyms/create'
    | '/schedules/$scheduleId'
    | '/schedules/create'
    | '/sessions/$sessionId'
    | '/workouts/$workoutId'
    | '/workouts/create'
    | '/body-weight/'
    | '/exercise-log/'
    | '/exercises/'
    | '/gyms/'
    | '/schedules/'
    | '/workouts/'
    | '/exercises/$exerciseId'
    | '/exercises/create'
    | '/muscle-groups/$muscleGroupId'
    | '/muscle-groups/create'
    | '/muscle-groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/verify-email'
    | '/api/$'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/exercises'
    | '/body-weight/$bodyWeightId'
    | '/body-weight/create'
    | '/gyms/$gymId'
    | '/gyms/create'
    | '/schedules/$scheduleId'
    | '/schedules/create'
    | '/sessions/$sessionId'
    | '/workouts/$workoutId'
    | '/workouts/create'
    | '/body-weight'
    | '/exercise-log'
    | '/gyms'
    | '/schedules'
    | '/workouts'
    | '/exercises/$exerciseId'
    | '/exercises/create'
    | '/muscle-groups/$muscleGroupId'
    | '/muscle-groups/create'
    | '/muscle-groups'
  id:
    | '__root__'
    | '/(private)/_dashboard'
    | '/(public)/_auth'
    | '/(public)/verify-email'
    | '/api/$'
    | '/(public)/'
    | '/(private)/_dashboard/_admin'
    | '/(private)/_dashboard/body-weight'
    | '/(private)/_dashboard/gyms'
    | '/(private)/_dashboard/schedules'
    | '/(private)/_dashboard/workouts'
    | '/(private)/_dashboard/dashboard'
    | '/(public)/_auth/forgot-password'
    | '/(public)/_auth/reset-password'
    | '/(public)/_auth/signin'
    | '/(public)/_auth/signup'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/(private)/_dashboard/_admin/exercises'
    | '/(private)/_dashboard/_admin/muscle-groups'
    | '/(private)/_dashboard/body-weight/$bodyWeightId'
    | '/(private)/_dashboard/body-weight/create'
    | '/(private)/_dashboard/gyms/$gymId'
    | '/(private)/_dashboard/gyms/create'
    | '/(private)/_dashboard/schedules/$scheduleId'
    | '/(private)/_dashboard/schedules/create'
    | '/(private)/_dashboard/sessions/$sessionId'
    | '/(private)/_dashboard/workouts/$workoutId'
    | '/(private)/_dashboard/workouts/create'
    | '/(private)/_dashboard/body-weight/'
    | '/(private)/_dashboard/exercise-log/'
    | '/(private)/_dashboard/exercises/'
    | '/(private)/_dashboard/gyms/'
    | '/(private)/_dashboard/schedules/'
    | '/(private)/_dashboard/workouts/'
    | '/(private)/_dashboard/_admin/exercises/$exerciseId'
    | '/(private)/_dashboard/_admin/exercises/create'
    | '/(private)/_dashboard/_admin/muscle-groups/$muscleGroupId'
    | '/(private)/_dashboard/_admin/muscle-groups/create'
    | '/(private)/_dashboard/_admin/muscle-groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateDashboardRouteRoute: typeof privateDashboardRouteRouteWithChildren
  publicAuthRouteRoute: typeof publicAuthRouteRouteWithChildren
  publicVerifyEmailRoute: typeof publicVerifyEmailRoute
  ApiSplatRoute: typeof ApiSplatRoute
  publicIndexRoute: typeof publicIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)/_dashboard': {
      id: '/(private)/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_auth': {
      id: '/(public)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/verify-email': {
      id: '/(public)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof publicVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_dashboard/_admin': {
      id: '/(private)/_dashboard/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateDashboardAdminRouteRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/body-weight': {
      id: '/(private)/_dashboard/body-weight'
      path: '/body-weight'
      fullPath: '/body-weight'
      preLoaderRoute: typeof privateDashboardBodyWeightRouteRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/dashboard': {
      id: '/(private)/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privateDashboardDashboardRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/gyms': {
      id: '/(private)/_dashboard/gyms'
      path: '/gyms'
      fullPath: '/gyms'
      preLoaderRoute: typeof privateDashboardGymsRouteRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/schedules': {
      id: '/(private)/_dashboard/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof privateDashboardSchedulesRouteRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/workouts': {
      id: '/(private)/_dashboard/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof privateDashboardWorkoutsRouteRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(public)/_auth/forgot-password': {
      id: '/(public)/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicAuthForgotPasswordRouteImport
      parentRoute: typeof publicAuthRouteRoute
    }
    '/(public)/_auth/reset-password': {
      id: '/(public)/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof publicAuthResetPasswordRouteImport
      parentRoute: typeof publicAuthRouteRoute
    }
    '/(public)/_auth/signin': {
      id: '/(public)/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof publicAuthSigninRouteImport
      parentRoute: typeof publicAuthRouteRoute
    }
    '/(public)/_auth/signup': {
      id: '/(public)/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof publicAuthSignupRouteImport
      parentRoute: typeof publicAuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_dashboard/_admin/exercises': {
      id: '/(private)/_dashboard/_admin/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof privateDashboardAdminExercisesRouteRouteImport
      parentRoute: typeof privateDashboardAdminRouteRoute
    }
    '/(private)/_dashboard/_admin/muscle-groups': {
      id: '/(private)/_dashboard/_admin/muscle-groups'
      path: '/muscle-groups'
      fullPath: '/muscle-groups'
      preLoaderRoute: typeof privateDashboardAdminMuscleGroupsRouteRouteImport
      parentRoute: typeof privateDashboardAdminRouteRoute
    }
    '/(private)/_dashboard/body-weight/': {
      id: '/(private)/_dashboard/body-weight/'
      path: '/'
      fullPath: '/body-weight/'
      preLoaderRoute: typeof privateDashboardBodyWeightIndexRouteImport
      parentRoute: typeof privateDashboardBodyWeightRouteRoute
    }
    '/(private)/_dashboard/body-weight/$bodyWeightId': {
      id: '/(private)/_dashboard/body-weight/$bodyWeightId'
      path: '/$bodyWeightId'
      fullPath: '/body-weight/$bodyWeightId'
      preLoaderRoute: typeof privateDashboardBodyWeightBodyWeightIdRouteImport
      parentRoute: typeof privateDashboardBodyWeightRouteRoute
    }
    '/(private)/_dashboard/body-weight/create': {
      id: '/(private)/_dashboard/body-weight/create'
      path: '/create'
      fullPath: '/body-weight/create'
      preLoaderRoute: typeof privateDashboardBodyWeightCreateRouteImport
      parentRoute: typeof privateDashboardBodyWeightRouteRoute
    }
    '/(private)/_dashboard/exercise-log/': {
      id: '/(private)/_dashboard/exercise-log/'
      path: '/exercise-log'
      fullPath: '/exercise-log/'
      preLoaderRoute: typeof privateDashboardExerciseLogIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/exercises/': {
      id: '/(private)/_dashboard/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof privateDashboardExercisesIndexRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/gyms/': {
      id: '/(private)/_dashboard/gyms/'
      path: '/'
      fullPath: '/gyms/'
      preLoaderRoute: typeof privateDashboardGymsIndexRouteImport
      parentRoute: typeof privateDashboardGymsRouteRoute
    }
    '/(private)/_dashboard/gyms/$gymId': {
      id: '/(private)/_dashboard/gyms/$gymId'
      path: '/$gymId'
      fullPath: '/gyms/$gymId'
      preLoaderRoute: typeof privateDashboardGymsGymIdRouteImport
      parentRoute: typeof privateDashboardGymsRouteRoute
    }
    '/(private)/_dashboard/gyms/create': {
      id: '/(private)/_dashboard/gyms/create'
      path: '/create'
      fullPath: '/gyms/create'
      preLoaderRoute: typeof privateDashboardGymsCreateRouteImport
      parentRoute: typeof privateDashboardGymsRouteRoute
    }
    '/(private)/_dashboard/schedules/': {
      id: '/(private)/_dashboard/schedules/'
      path: '/'
      fullPath: '/schedules/'
      preLoaderRoute: typeof privateDashboardSchedulesIndexRouteImport
      parentRoute: typeof privateDashboardSchedulesRouteRoute
    }
    '/(private)/_dashboard/schedules/$scheduleId': {
      id: '/(private)/_dashboard/schedules/$scheduleId'
      path: '/$scheduleId'
      fullPath: '/schedules/$scheduleId'
      preLoaderRoute: typeof privateDashboardSchedulesScheduleIdRouteImport
      parentRoute: typeof privateDashboardSchedulesRouteRoute
    }
    '/(private)/_dashboard/schedules/create': {
      id: '/(private)/_dashboard/schedules/create'
      path: '/create'
      fullPath: '/schedules/create'
      preLoaderRoute: typeof privateDashboardSchedulesCreateRouteImport
      parentRoute: typeof privateDashboardSchedulesRouteRoute
    }
    '/(private)/_dashboard/sessions/$sessionId': {
      id: '/(private)/_dashboard/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof privateDashboardSessionsSessionIdRouteImport
      parentRoute: typeof privateDashboardRouteRoute
    }
    '/(private)/_dashboard/workouts/': {
      id: '/(private)/_dashboard/workouts/'
      path: '/'
      fullPath: '/workouts/'
      preLoaderRoute: typeof privateDashboardWorkoutsIndexRouteImport
      parentRoute: typeof privateDashboardWorkoutsRouteRoute
    }
    '/(private)/_dashboard/workouts/$workoutId': {
      id: '/(private)/_dashboard/workouts/$workoutId'
      path: '/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof privateDashboardWorkoutsWorkoutIdRouteImport
      parentRoute: typeof privateDashboardWorkoutsRouteRoute
    }
    '/(private)/_dashboard/workouts/create': {
      id: '/(private)/_dashboard/workouts/create'
      path: '/create'
      fullPath: '/workouts/create'
      preLoaderRoute: typeof privateDashboardWorkoutsCreateRouteImport
      parentRoute: typeof privateDashboardWorkoutsRouteRoute
    }
    '/(private)/_dashboard/_admin/exercises/$exerciseId': {
      id: '/(private)/_dashboard/_admin/exercises/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof privateDashboardAdminExercisesExerciseIdRouteImport
      parentRoute: typeof privateDashboardAdminExercisesRouteRoute
    }
    '/(private)/_dashboard/_admin/exercises/create': {
      id: '/(private)/_dashboard/_admin/exercises/create'
      path: '/create'
      fullPath: '/exercises/create'
      preLoaderRoute: typeof privateDashboardAdminExercisesCreateRouteImport
      parentRoute: typeof privateDashboardAdminExercisesRouteRoute
    }
    '/(private)/_dashboard/_admin/muscle-groups/': {
      id: '/(private)/_dashboard/_admin/muscle-groups/'
      path: '/'
      fullPath: '/muscle-groups/'
      preLoaderRoute: typeof privateDashboardAdminMuscleGroupsIndexRouteImport
      parentRoute: typeof privateDashboardAdminMuscleGroupsRouteRoute
    }
    '/(private)/_dashboard/_admin/muscle-groups/$muscleGroupId': {
      id: '/(private)/_dashboard/_admin/muscle-groups/$muscleGroupId'
      path: '/$muscleGroupId'
      fullPath: '/muscle-groups/$muscleGroupId'
      preLoaderRoute: typeof privateDashboardAdminMuscleGroupsMuscleGroupIdRouteImport
      parentRoute: typeof privateDashboardAdminMuscleGroupsRouteRoute
    }
    '/(private)/_dashboard/_admin/muscle-groups/create': {
      id: '/(private)/_dashboard/_admin/muscle-groups/create'
      path: '/create'
      fullPath: '/muscle-groups/create'
      preLoaderRoute: typeof privateDashboardAdminMuscleGroupsCreateRouteImport
      parentRoute: typeof privateDashboardAdminMuscleGroupsRouteRoute
    }
  }
}

interface privateDashboardAdminExercisesRouteRouteChildren {
  privateDashboardAdminExercisesExerciseIdRoute: typeof privateDashboardAdminExercisesExerciseIdRoute
  privateDashboardAdminExercisesCreateRoute: typeof privateDashboardAdminExercisesCreateRoute
}

const privateDashboardAdminExercisesRouteRouteChildren: privateDashboardAdminExercisesRouteRouteChildren =
  {
    privateDashboardAdminExercisesExerciseIdRoute:
      privateDashboardAdminExercisesExerciseIdRoute,
    privateDashboardAdminExercisesCreateRoute:
      privateDashboardAdminExercisesCreateRoute,
  }

const privateDashboardAdminExercisesRouteRouteWithChildren =
  privateDashboardAdminExercisesRouteRoute._addFileChildren(
    privateDashboardAdminExercisesRouteRouteChildren,
  )

interface privateDashboardAdminMuscleGroupsRouteRouteChildren {
  privateDashboardAdminMuscleGroupsMuscleGroupIdRoute: typeof privateDashboardAdminMuscleGroupsMuscleGroupIdRoute
  privateDashboardAdminMuscleGroupsCreateRoute: typeof privateDashboardAdminMuscleGroupsCreateRoute
  privateDashboardAdminMuscleGroupsIndexRoute: typeof privateDashboardAdminMuscleGroupsIndexRoute
}

const privateDashboardAdminMuscleGroupsRouteRouteChildren: privateDashboardAdminMuscleGroupsRouteRouteChildren =
  {
    privateDashboardAdminMuscleGroupsMuscleGroupIdRoute:
      privateDashboardAdminMuscleGroupsMuscleGroupIdRoute,
    privateDashboardAdminMuscleGroupsCreateRoute:
      privateDashboardAdminMuscleGroupsCreateRoute,
    privateDashboardAdminMuscleGroupsIndexRoute:
      privateDashboardAdminMuscleGroupsIndexRoute,
  }

const privateDashboardAdminMuscleGroupsRouteRouteWithChildren =
  privateDashboardAdminMuscleGroupsRouteRoute._addFileChildren(
    privateDashboardAdminMuscleGroupsRouteRouteChildren,
  )

interface privateDashboardAdminRouteRouteChildren {
  privateDashboardAdminExercisesRouteRoute: typeof privateDashboardAdminExercisesRouteRouteWithChildren
  privateDashboardAdminMuscleGroupsRouteRoute: typeof privateDashboardAdminMuscleGroupsRouteRouteWithChildren
}

const privateDashboardAdminRouteRouteChildren: privateDashboardAdminRouteRouteChildren =
  {
    privateDashboardAdminExercisesRouteRoute:
      privateDashboardAdminExercisesRouteRouteWithChildren,
    privateDashboardAdminMuscleGroupsRouteRoute:
      privateDashboardAdminMuscleGroupsRouteRouteWithChildren,
  }

const privateDashboardAdminRouteRouteWithChildren =
  privateDashboardAdminRouteRoute._addFileChildren(
    privateDashboardAdminRouteRouteChildren,
  )

interface privateDashboardBodyWeightRouteRouteChildren {
  privateDashboardBodyWeightBodyWeightIdRoute: typeof privateDashboardBodyWeightBodyWeightIdRoute
  privateDashboardBodyWeightCreateRoute: typeof privateDashboardBodyWeightCreateRoute
  privateDashboardBodyWeightIndexRoute: typeof privateDashboardBodyWeightIndexRoute
}

const privateDashboardBodyWeightRouteRouteChildren: privateDashboardBodyWeightRouteRouteChildren =
  {
    privateDashboardBodyWeightBodyWeightIdRoute:
      privateDashboardBodyWeightBodyWeightIdRoute,
    privateDashboardBodyWeightCreateRoute:
      privateDashboardBodyWeightCreateRoute,
    privateDashboardBodyWeightIndexRoute: privateDashboardBodyWeightIndexRoute,
  }

const privateDashboardBodyWeightRouteRouteWithChildren =
  privateDashboardBodyWeightRouteRoute._addFileChildren(
    privateDashboardBodyWeightRouteRouteChildren,
  )

interface privateDashboardGymsRouteRouteChildren {
  privateDashboardGymsGymIdRoute: typeof privateDashboardGymsGymIdRoute
  privateDashboardGymsCreateRoute: typeof privateDashboardGymsCreateRoute
  privateDashboardGymsIndexRoute: typeof privateDashboardGymsIndexRoute
}

const privateDashboardGymsRouteRouteChildren: privateDashboardGymsRouteRouteChildren =
  {
    privateDashboardGymsGymIdRoute: privateDashboardGymsGymIdRoute,
    privateDashboardGymsCreateRoute: privateDashboardGymsCreateRoute,
    privateDashboardGymsIndexRoute: privateDashboardGymsIndexRoute,
  }

const privateDashboardGymsRouteRouteWithChildren =
  privateDashboardGymsRouteRoute._addFileChildren(
    privateDashboardGymsRouteRouteChildren,
  )

interface privateDashboardSchedulesRouteRouteChildren {
  privateDashboardSchedulesScheduleIdRoute: typeof privateDashboardSchedulesScheduleIdRoute
  privateDashboardSchedulesCreateRoute: typeof privateDashboardSchedulesCreateRoute
  privateDashboardSchedulesIndexRoute: typeof privateDashboardSchedulesIndexRoute
}

const privateDashboardSchedulesRouteRouteChildren: privateDashboardSchedulesRouteRouteChildren =
  {
    privateDashboardSchedulesScheduleIdRoute:
      privateDashboardSchedulesScheduleIdRoute,
    privateDashboardSchedulesCreateRoute: privateDashboardSchedulesCreateRoute,
    privateDashboardSchedulesIndexRoute: privateDashboardSchedulesIndexRoute,
  }

const privateDashboardSchedulesRouteRouteWithChildren =
  privateDashboardSchedulesRouteRoute._addFileChildren(
    privateDashboardSchedulesRouteRouteChildren,
  )

interface privateDashboardWorkoutsRouteRouteChildren {
  privateDashboardWorkoutsWorkoutIdRoute: typeof privateDashboardWorkoutsWorkoutIdRoute
  privateDashboardWorkoutsCreateRoute: typeof privateDashboardWorkoutsCreateRoute
  privateDashboardWorkoutsIndexRoute: typeof privateDashboardWorkoutsIndexRoute
}

const privateDashboardWorkoutsRouteRouteChildren: privateDashboardWorkoutsRouteRouteChildren =
  {
    privateDashboardWorkoutsWorkoutIdRoute:
      privateDashboardWorkoutsWorkoutIdRoute,
    privateDashboardWorkoutsCreateRoute: privateDashboardWorkoutsCreateRoute,
    privateDashboardWorkoutsIndexRoute: privateDashboardWorkoutsIndexRoute,
  }

const privateDashboardWorkoutsRouteRouteWithChildren =
  privateDashboardWorkoutsRouteRoute._addFileChildren(
    privateDashboardWorkoutsRouteRouteChildren,
  )

interface privateDashboardRouteRouteChildren {
  privateDashboardAdminRouteRoute: typeof privateDashboardAdminRouteRouteWithChildren
  privateDashboardBodyWeightRouteRoute: typeof privateDashboardBodyWeightRouteRouteWithChildren
  privateDashboardGymsRouteRoute: typeof privateDashboardGymsRouteRouteWithChildren
  privateDashboardSchedulesRouteRoute: typeof privateDashboardSchedulesRouteRouteWithChildren
  privateDashboardWorkoutsRouteRoute: typeof privateDashboardWorkoutsRouteRouteWithChildren
  privateDashboardDashboardRoute: typeof privateDashboardDashboardRoute
  privateDashboardSessionsSessionIdRoute: typeof privateDashboardSessionsSessionIdRoute
  privateDashboardExerciseLogIndexRoute: typeof privateDashboardExerciseLogIndexRoute
  privateDashboardExercisesIndexRoute: typeof privateDashboardExercisesIndexRoute
}

const privateDashboardRouteRouteChildren: privateDashboardRouteRouteChildren = {
  privateDashboardAdminRouteRoute: privateDashboardAdminRouteRouteWithChildren,
  privateDashboardBodyWeightRouteRoute:
    privateDashboardBodyWeightRouteRouteWithChildren,
  privateDashboardGymsRouteRoute: privateDashboardGymsRouteRouteWithChildren,
  privateDashboardSchedulesRouteRoute:
    privateDashboardSchedulesRouteRouteWithChildren,
  privateDashboardWorkoutsRouteRoute:
    privateDashboardWorkoutsRouteRouteWithChildren,
  privateDashboardDashboardRoute: privateDashboardDashboardRoute,
  privateDashboardSessionsSessionIdRoute:
    privateDashboardSessionsSessionIdRoute,
  privateDashboardExerciseLogIndexRoute: privateDashboardExerciseLogIndexRoute,
  privateDashboardExercisesIndexRoute: privateDashboardExercisesIndexRoute,
}

const privateDashboardRouteRouteWithChildren =
  privateDashboardRouteRoute._addFileChildren(
    privateDashboardRouteRouteChildren,
  )

interface publicAuthRouteRouteChildren {
  publicAuthForgotPasswordRoute: typeof publicAuthForgotPasswordRoute
  publicAuthResetPasswordRoute: typeof publicAuthResetPasswordRoute
  publicAuthSigninRoute: typeof publicAuthSigninRoute
  publicAuthSignupRoute: typeof publicAuthSignupRoute
}

const publicAuthRouteRouteChildren: publicAuthRouteRouteChildren = {
  publicAuthForgotPasswordRoute: publicAuthForgotPasswordRoute,
  publicAuthResetPasswordRoute: publicAuthResetPasswordRoute,
  publicAuthSigninRoute: publicAuthSigninRoute,
  publicAuthSignupRoute: publicAuthSignupRoute,
}

const publicAuthRouteRouteWithChildren = publicAuthRouteRoute._addFileChildren(
  publicAuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateDashboardRouteRoute: privateDashboardRouteRouteWithChildren,
  publicAuthRouteRoute: publicAuthRouteRouteWithChildren,
  publicVerifyEmailRoute: publicVerifyEmailRoute,
  ApiSplatRoute: ApiSplatRoute,
  publicIndexRoute: publicIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
